### ISSUE TITLE
dotenv-rails gem

### ISSUE THREAD

**Issue by jhsu802701** [novu/whale-of-a-tale#10]
How does the app work without the use of the dotenv-rails gem?  I noticed that it relies on having environment variables set in the .env file, but the dotenv-rails gem isn't in the Gemfile.  Why isn't the dotenv-rails gem necessary?

**Comment by jhsu802701** [comment]
OK, I see that the docker-compose.yml file specifies the use of the .env file for setting up the PostgreSQL database.

**Comment by arich** [comment]
👍 Docs: https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option
