### ISSUE TITLE
Setup for developing this app

### ISSUE THREAD

**Issue by jhsu802701** [novu/whale-of-a-tale#11]
What's the preferred setup for developing an app like this?

I assume that one terminal tab is needed for running the app server, a second terminal command (in the host OS) is needed for entering Git commands, and a third terminal tab is needed for other tasks.  In this third terminal tab, do you prepend all commands with "docker-compose run --rm web", or do you enter "docker-compose run --rm web /bin/sh" and type in rails/bundle/rake commands directly within the Docker container?

**Comment by arich** [comment]
I think it's up to you and your personal preference. The scenario you've outlined is roughly my preferred setup. 

Terminal Tab 1: `docker-compose up` or `docker-compose up web` if I'm not using background jobs and don't want them running. 
Terminal Tab 2: `make sh web` to run commands inside the container (https://github.com/novu/whale-of-a-tale/blob/master/Makefile#L21-L22)
Terminal Tab 3: git commands, anything else.

Typically I'll exit the container or just start a new terminal tab for git and other things I need to do locally.
