### ISSUE TITLE
Binstubs

### ISSUE THREAD

**Issue by jhsu802701** [novu/whale-of-a-tale#6]
What am I supposed to do about the binstubs?  Anytime I run the "rake" command, I get a long message about binstubs that begins with "Beginning in Rails 4, Rails ships with a `rails` binstub at ./bin/rails that should be used instead of the Bundler-generated `rails` binstub."  (I tried this app out in my preferred Debian-based Docker system and got this message as well.  I don't get this binstubs message in other Rails apps, so there must be something about the Whale App that I haven't adjusted to.)

**Comment by arich** [comment]
Addressed in https://github.com/novu/whale-of-a-tale/pull/13.

**Comment by arich** [comment]
Merged. Closing.
